vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        services:
           uri_prefix: /images/services
           upload_destination: '%kernel.project_dir%/public/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true
           inject_on_load: false

        produits:
           uri_prefix: /images/produits
           upload_destination: '%kernel.project_dir%/public/images/produits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true
           inject_on_load: false

        user:
           uri_prefix: /images/user
           upload_destination: '%kernel.project_dir%/public/images/user'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true
           inject_on_load: false